name: Build and deploy Aseprite (Windows only)

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-aseprite:
    name: Build Aseprite (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Setup Visual Studio environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Download Aseprite source
        run: |
          curl -o Aseprite-source.zip -L https://github.com/aseprite/aseprite/archive/refs/tags/v1.3.14.zip
          unzip Aseprite-source.zip -d aseprite
          mkdir -p aseprite/aseprite-1.3.14/build

      - name: Download Skia
        run: |
          curl -o Skia-Windows-Release-x64.zip -L https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip
          unzip Skia-Windows-Release-x64.zip -d skia

      - name: Set architecture
        shell: cmd
        run: call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64

      - name: Run CMake
        working-directory: aseprite/aseprite-1.3.14/build
        shell: cmd
        run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DLAF_BACKEND=skia -DSKIA_DIR=..\..\..\skia -DSKIA_LIBRARY_DIR=..\..\..\skia\out\Release-x64 -DSKIA_LIBRARY=..\..\..\skia\out\Release-x64\skia.lib -DOPENSSL_ROOT_DIR=C:\OpenSSL -DOPENSSL_USE_STATIC_LIBS=TRUE -G Ninja ..

      - name: Build with Ninja
        working-directory: aseprite/aseprite-1.3.14/build
        run: ninja aseprite

      - name: Clean up build
        working-directory: aseprite/aseprite-1.3.14/build/bin
        shell: bash
        run: rm -f gen modp_b64_gen gen.exe gen.exe.manifest modp_b64_gen.exe modp_b64_gen.exe.manifest

      - name: Add portable .ini file
        working-directory: aseprite/aseprite-1.3.14/build/bin
        run: echo '# This file is here so Aseprite behaves as a portable program' > aseprite.ini

      - name: Add Multilingual files
        working-directory: aseprite/aseprite-1.3.14/build/bin/data
        shell: bash
        run: |
          rm -f strings/*.ini
          curl -o strings-main.zip -L https://codeload.github.com/aseprite/strings/zip/refs/heads/main
          unzip strings-main.zip -d strings-main
          cp strings-main/strings-main/*.ini strings
          rm -rf strings-main

      - name: Rename Executable
        working-directory: aseprite/aseprite-1.3.14/build/bin
        run: ren aseprite.exe Aseprite.exe

      - name: Zip Release
        working-directory: aseprite/aseprite-1.3.14/build
        run: |
          mv bin Aseprite-v1.3.14-Windows-x64
          7z a -tzip Aseprite-v1.3.14-Windows-x64.zip Aseprite-v1.3.14-Windows-x64